services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_APP_NAME=${VITE_APP_NAME}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    labels:
      - traefik.enable=true
      - traefik.http.routers.memberfun-http.rule=Host(`memberfun.${DOMAIN}`)
      - traefik.http.routers.memberfun-http.entrypoints=http
      - traefik.http.routers.memberfun-http.middlewares=https-redirect
      - traefik.http.routers.memberfun-https.rule=Host(`memberfun.${DOMAIN}`)
      - traefik.http.routers.memberfun-https.entrypoints=https
      - traefik.http.routers.memberfun-https.tls=true
      - traefik.http.routers.memberfun-https.tls.certresolver=le
      - traefik.http.routers.memberfun-https.service=memberfun-service
      - traefik.http.services.memberfun-service.loadbalancer.server.port=5173
    networks:
      - traefik-public
    command: npm run dev -- --host 0.0.0.0

  wordpress:
    # image: wordpress:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: wordpress
    ports:
      - "8181:80"
    environment:
      - APACHE_SERVER_NAME=`memberfun-api.${DOMAIN}`
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      # - WORDPRESS_CONFIG_EXTRA="define('FORCE_SSL_ADMIN', true);"
      - WORDPRESS_DEBUG=1
      - WORDPRESS_CONFIG_EXTRA=
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('UPLOAD_MAX_FILESIZE', '256M');
        define('POST_MAX_SIZE', '256M');
        define('JWT_AUTH_SECRET_KEY', '${JWT_AUTH_SECRET_KEY:-dev}');
        define('JWT_AUTH_CORS_ENABLE', '${JWT_AUTH_CORS_ENABLE:-true}');
        define('WP_ENVIRONMENT_TYPE', '${WP_ENVIRONMENT_TYPE:-local}');
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_REDIS_PASSWORD', '${REDIS_PASSWORD:-redis_password}');
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress-http.rule=Host(`memberfun-api.${DOMAIN}`)
      - traefik.http.routers.wordpress-http.entrypoints=http
      - traefik.http.routers.wordpress-http.middlewares=https-redirect
      - traefik.http.routers.wordpress-https.rule=Host(`memberfun-api.${DOMAIN}`)
      - traefik.http.routers.wordpress-https.entrypoints=https
      - traefik.http.routers.wordpress-https.tls=true
      - traefik.http.routers.wordpress-https.tls.certresolver=le
      - traefik.http.routers.wordpress-https.service=wordpress-service
      - traefik.http.services.wordpress-service.loadbalancer.server.port=80
    volumes:
      - wordpress:/var/www/html
      - ./backend/wp-content:/var/www/html/wp-content
      - ./backend/apache-servername.conf:/etc/apache2/conf-available/servername.conf
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - traefik-public

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    networks:
      - traefik-public

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`memberfun-adminer.${DOMAIN}`)
      - traefik.http.routers.adminer.entrypoints=http
      - traefik.http.routers.adminer.middlewares=https-redirect
      - traefik.http.routers.adminer-https.rule=Host(`memberfun-adminer.${DOMAIN}`)
      - traefik.http.routers.adminer-https.entrypoints=https
      - traefik.http.routers.adminer-https.tls=true
      - traefik.http.routers.adminer-https.tls.certresolver=le
      - traefik.http.services.adminer-service.loadbalancer.server.port=8080
    networks:
      - traefik-public

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  wordpress:
  mysql:
  redis:
