version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000/wp-json}
      - VITE_APP_NAME=${VITE_APP_NAME:-MemberFun-Dev}
    command: npm run dev -- --host 0.0.0.0

  wordpress:
    image: wordpress:latest
    container_name: wordpress-dev
    ports:
      - "8000:80"
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-wordpress_password}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DEBUG=1
      - WORDPRESS_CONFIG_EXTRA=
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('UPLOAD_MAX_FILESIZE', '256M');
        define('POST_MAX_SIZE', '256M');
        define('JWT_AUTH_SECRET_KEY', '${JWT_AUTH_SECRET_KEY:-dev}');
        define('JWT_AUTH_CORS_ENABLE', '${JWT_AUTH_CORS_ENABLE:-true}');
        define('WP_ENVIRONMENT_TYPE', '${WP_ENVIRONMENT_TYPE:-local}');
    volumes:
      - wordpress_data:/var/www/html
      - ./backend/wp-content:/var/www/html/wp-content
      - ./backend/.htaccess:/var/www/html/.htaccess
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: mysql-dev
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-somewordpress}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-wordpress}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-wordpress_password}
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password}
    volumes:
      - redis_data:/data

volumes:
  wordpress_data:
  mysql_data:
  redis_data: 